export const SET_SIDE_MENU = 'SET_SIDE_MENU';
export const UPDATE_SELECTED_TRIP_DAY_ID = 'UPDATE_SELECTED_TRIP_DAY_ID';
export const OPEN_TRIP_FORM = 'OPEN_TRIP_FORM';
export const OPEN_TRIP_DAY_FORM = 'OPEN_TRIP_DAY_FORM';
export const OPEN_TRIP_EVENT_FORM = 'OPEN_TRIP_EVENT_FORM';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CREATE_ALERT = 'CREATE_ALERT';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const FETCHING_TRIP_LIST = 'FETCHING_TRIP_LIST';
export const FETCHING_TRIP_LIST_SUCCESS = 'FETCHING_TRIP_LIST_SUCCESS';
export const FETCHING_TRIP_LIST_FAILURE = 'FETCHING_TRIP_LIST_FAILURE';

export const FETCHING_TRIP_DETAIL = 'FETCHING_TRIP_DETAIL';
export const FETCHING_TRIP_DETAIL_SUCCESS = 'FETCHING_TRIP_DETAIL_SUCCESS';
export const FETCHING_TRIP_DETAIL_FAILURE = 'FETCHING_TRIP_DETAIL_FAILURE';

export const CREATING_TRIP = 'CREATING_TRIP';
export const CREATING_TRIP_SUCCESS = 'CREATING_TRIP_SUCCESS';
export const CREATING_TRIP_FAILURE = 'CREATING_TRIP_FAILURE';

export const CREATING_TRIP_DAY = 'CREATING_TRIP_DAY';
export const CREATING_TRIP_DAY_SUCCESS = 'CREATING_TRIP_DAY_SUCCESS';
export const CREATING_TRIP_DAY_FAILURE = 'CREATING_TRIP_DAY_FAILURE';

export const CREATING_TRIP_EVENT = 'CREATING_TRIP_EVENT';
export const CREATING_TRIP_EVENT_SUCCESS = 'CREATING_TRIP_EVENT_SUCCESS';
export const CREATING_TRIP_EVENT_FAILURE = 'CREATING_TRIP_EVENT_FAILURE';
