export const SET_SIDE_MENU = 'SET_SIDE_MENU';
export const SELECTED_TRIP_DAY_ID = 'SELECTED_TRIP_DAY_ID';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const FETCHING_TRIP_LIST = 'FETCHING_TRIP_LIST';
export const FETCHING_TRIP_LIST_SUCCESS = 'FETCHING_TRIP_LIST_SUCCESS';
export const FETCHING_TRIP_LIST_FAILURE = 'FETCHING_TRIP_LIST_FAILURE';

export const FETCHING_TRIP_DETAIL = 'FETCHING_TRIP_DETAIL';
export const FETCHING_TRIP_DETAIL_SUCCESS = 'FETCHING_TRIP_DETAIL_SUCCESS';
export const FETCHING_TRIP_DETAIL_FAILURE = 'FETCHING_TRIP_DETAIL_FAILURE';
